### ISSUE TITLE
feature request: Support for 3206MSO

### ISSUE THREAD

**Issue by tdcox** [azonenberg/scopehal-pico-bridge#1]
Please could you consider support for the Pico 3206 MSO?

Thank you.

**Comment by bvernoux** [comment]
See https://github.com/glscopeclient/scopehal-pico-bridge/pull/19
See also https://github.com/glscopeclient/scopehal/pull/481

**Comment by bvernoux** [comment]
Picoscope3000 series+MSO are supported now (https://github.com/glscopeclient/scopehal-pico-bridge/pull/19 & https://github.com/glscopeclient/scopehal/pull/481 are merged now)
@azonenberg Last point is to synchronize https://github.com/glscopeclient/scopehal-apps to use latest https://github.com/glscopeclient/scopehal
@tdcox Please provide a feedback and close that issue

**Comment by tdcox** [comment]
Would love to test this but it doesn’t appear to be included in the MSYS package and there are no instructions for building it.

**Comment by bvernoux** [comment]
You can use those steps with msys2/mingw64

All following steps are to be done in a MinGW64 shell (notin a MSYS shell, which also getsinstalled by the MSYS2 installer)
pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-make
pacman -S mingw-w64-x86_64-glm mingw-w64-x86_64-libsigc++ mingw-w64-x86_64-gtkmm3 mingw-w64-x86_64-yaml-cpp mingw-w64-x86_64-glew
pacman -S mingw-w64-x86_64-opencl-icd

##################################
# For Release Windows
##################################
cd ~
git clone https://github.com/azonenberg/scopehal-apps.git --recurse -submodules

cd ~
cd scopehal-pico-bridge
mkdir build
cd build
cmake -G"MinGW Makefiles" -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Release ..
mingw32-make -j8

cd ~
mkdir scopehal-pico-bridge_build_release
cd ./scopehal-pico-bridge/build
cp C:/msys64/mingw64/bin/libstdc++-6.dll ~/scopehal-pico-bridge_build_release/
cp C:/msys64/mingw64/bin/libgcc_s_seh-1.dll ~/scopehal-pico-bridge_build_release/
cp C:/msys64/mingw64/bin/libwinpthread-1.dll ~/scopehal-pico-bridge_build_release/
cp ./src/ps6000d/ps6000d.exe ~/scopehal-pico-bridge_build_release/
cp ./lib/log/liblog.dll ~/scopehal-pico-bridge_build_release/
