### ISSUE TITLE
Communication sample

### ISSUE THREAD

**Issue by danielkucera** [azonenberg/scopehal-pico-bridge#16]
Hi,

I am trying to mimic this server in python but I struggle with correct data bytes packing.
Could you please provide a sample capture of communication so I can compare to what I am sending?
Or make a dummy endpoint without need for the the actual hardware?

**Comment by azonenberg** [comment]
All fields are host byte order (i.e. little endian unless you're on a really weird platform). There's no padding, the fields you see here are sent consecutively with no gaps.

There's a SCPI interface on TCP 5025 that should be fairly straightforward to understand.

As far as the binary protocol on TCP 5026, it's output only (data sent to the bridge is ignored). Every trigger, the bridge sends the following:
<pre>
uint16 numChannels //number of channels in the waveform, may be less than total scope hardware channel count if some are off
int64 sampleInterval //femtoseconds between samples

for i in 0 to numChannels-1
    uint64 channelID //identifier of channel within the instrument. usually 0-3/7 are analog, then digital/trigger
    uint64 numSamples //number of samples in the waveform
    if channel is analog
        float32 scale //scale factor to convert raw ADC codes to volts
        float32 offset //vertical offset to convert raw ADC codes to volts
        float32 trigphase //phase shift, in samples, from trigger event to ADC clock
        int16 rawADCSamples[numSamples] //raw ADC samples, padded to 16 bits (-32767 = min scale, +32768 = max scale)
    if channel is digital
        float32 trigphase //same as for analog
        uint16 rawDigitalSamples[numSamples] //high byte always 0x00 for compatibility with Pico API, low byte has eight 1-bit MSO samples
</pre>

**Comment by azonenberg** [comment]
That said, given that this is not currently a stable API (and the driver contains a lot of hard coded logic for various features/quirks of the Pico platform like sample rate or what channels can be used under various conditions) I strongly recommend against actually using the PicoOscilloscope driver in libscopehal for third party hardware. You can copy the basic architecture and build a new driver based on the same code. But don't actually use the driver as-is or you'll likely find random breakage etc.

**Comment by danielkucera** [comment]
Thank you, that helped.
For the level of functionality I have implemented so far it works fine. When I hit some roadblocks, I'll do as yo suggest.
Here is what I have so far https://github.com/danielkucera/pyhantek
