### ISSUE TITLE
PicoScope 3000 Series 

### ISSUE THREAD

**Issue by keesj-exset** [azonenberg/scopehal-pico-bridge#17]
Hi,

I am trying scopehal pico brigde on a PicoScope 3000 Series 3406D but I can not view a waveform. I am getting the following messages (from ps6000d) 

```
Looking for a PicoScope 6000 series instrument to open...
Looking for a PicoScope 3000 series instrument to open...
Successfully opened instrument
    Driver version:   PS3000A Linux Driver, 2.1.91.3194
    USB version:      3.0
    Hardware version: 1
    Variant info:     3406D
    Batch/serial:     FW896/0067
    Cal date:         21Jun18
    Kernel ver:       0.0
    Digital HW ver:   1
    Analog HW ver:    1
    FW ver 1:         1.7.5.0
    FW ver 2:         1.0.67.0
    Driver path:      /opt/picoscope/lib/libps3000a.so.2
    Shadow cal:       Default
    IPP version:      libpicoipp.so Linux Driver, 2.1.91.3194
Client connected to SCPI socket
ERROR: ps6000aSigGenRange failed, code 0xc
ERROR: ps6000aSigGenApply failed, code 0xc
ERROR: ps6000aSigGenWaveform failed, code 0xc
ERROR: ps6000aSigGenRange failed, code 0xc
ERROR: ps6000aSigGenApply failed, code 0xc
ERROR: ps6000aSigGenWaveformDutyCycle failed, code 0xc
ERROR: ps6000aSigGenRange failed, code 0xc
ERROR: ps6000aSigGenApply failed, code 0xc
ERROR: ps6000aSigGenFrequency failed, code 0xc (freq=1000000.000000)
ERROR: ps6000aSigGenRange failed, code 0xc
ERROR: ps6000aSigGenApply failed, code 0xc
ERROR: ps6000aSigGenRange failed, code 0xc
ERROR: ps6000aSigGenApply failed, code 0xc
ERROR: ps6000aSigGenRange failed, code 0xc
ERROR: ps6000aSigGenApply failed, code 0xc
ERROR: ps6000aSigGenRange failed, code 0xc
ERROR: ps6000aSigGenApply failed, code 0xc
ERROR: ps6000aSigGenRange failed, code 0xc
ERROR: ps6000aSigGenApply failed, code 0xc
Ignoring START command because trigger is already armed
Ignoring START command because trigger is already armed

```

**Comment by azonenberg** [comment]
You're getting errors about ps6000* series functions, interesting. Seems like it correctly identifies the instrument as a 3000 series early on, but then starts treating it as a 6000 and things go sideways.

**Comment by azonenberg** [comment]
Ok so... the ps6000aSigGen errors seem to be harmless. There's no function generator support in ps6000d for the 3000 series yet, so those functions assume they're dealing with a 6000 series instrument and fail when given anything else.

On the glscopeclient side, are you sure that the instrument actually has a valid trigger configured? The default in glscopeclient is to run in normal trigger mode (we don't actually support auto trigger yet, that's a pending TODO item), while the PicoScope software defaults to auto trigger. So if you don't have a trigger correctly configured and actually firing, you won't see anything.

**Comment by azonenberg** [comment]
Filed a separate issue #18 for the missing function generator support on the 3000 series.

**Comment by keesj-exset** [comment]
Hello , I did not know about the trigger setup but I think I configured it properly now still. 

![Screenshot from 2022-07-05 13-34-13](https://user-images.githubusercontent.com/62298192/177318611-d7c7cd80-d0b1-4c86-af6f-cc034ac613c7.png)

**Comment by keesj-exset** [comment]
Another hint is;
* Unknown PicoScope model "3406D" in the screenshot above.

**Comment by azonenberg** [comment]
Yeah. 3000 series support in libscopehal is still incomplete. There just might not be enough driver-side code to work properly.

I can see what I can do as far as adding it, but it will be hard without hardware to test on.

@noopwafel I think you had some success with 3000 series? What's the status of that?

**Comment by bvernoux** [comment]
See https://github.com/glscopeclient/scopehal-pico-bridge/pull/19
See also https://github.com/glscopeclient/scopehal/pull/481
Note: It work fine on my side waiting PRs merge for that first version (need more test on MSO channels)

**Comment by azonenberg** [comment]
@bvernoux are we good to close this issue or are there still pending items?

**Comment by bvernoux** [comment]
Waiting https://github.com/glscopeclient/scopehal/pull/481
To be merged as so far no anyone can test it without this PR merged

**Comment by bvernoux** [comment]
@keesj-exset Picoscope3000 series+MSO are supported now (https://github.com/glscopeclient/scopehal-pico-bridge/pull/19 & https://github.com/glscopeclient/scopehal/pull/481 are merged now)
@azonenberg  Last point is to synchronize https://github.com/glscopeclient/scopehal-apps to use latest https://github.com/glscopeclient/scopehal
@keesj-exset Please provide a feedback and close that issue
